# .github/workflows/build.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: build

permissions:
  contents: read

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Nota: Reemplazar "main, master" con las branches principales que se manejen (ej.: "main, develop")
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      # Execute Gradle commands in GitHub Actions workflows
      - uses: gradle/actions/setup-gradle@v5

      - name: Execute tests with coverage
        run: ./gradlew clean runOnGitHub

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v5
        with:
          name: jacoco-report
          path: build/reports/jacoco/
